sources:
  - type: maven
    path: parent-pom/pom.xml
  - type: maven
    path: exasol-jdbc/pom.xml
    modules:
      - maven_central
      - integration_tests
    parentPom:
      groupId: "com.exasol"
      artifactId: "spark-connector-parent-pom"
      version: "${revision}"
      relativePath: "../parent-pom/pom.xml"
  - type: maven
    path: exasol-s3/pom.xml
    modules:
      - maven_central
      - integration_tests
    parentPom:
      groupId: "com.exasol"
      artifactId: "spark-connector-parent-pom"
      version: "${revision}"
      relativePath: "../parent-pom/pom.xml"
version:
  fromSource: parent-pom/pom.xml
excludes:
  - regex: "(?s)E-PK-CORE-62: The project's README.md does not contain a valid badges block. Please add or replace the following badges:.*"
  - "E-PK-CORE-18: Outdated content: '.github/workflows/ci-build-next-java.yml'"
  - "E-PK-CORE-18: Outdated content: '.github/workflows/ci-build.yml'"
  - "E-PK-CORE-18: Outdated content: '.github/workflows/release_droid_upload_github_release_assets.yml'"
  - "E-PK-CORE-18: Outdated content: '.github/workflows/release_droid_release_on_maven_central.yml'"
  - "E-PK-CORE-18: Outdated content: '.settings/org.eclipse.jdt.core.prefs'"
  - regex: ".*W-PK-CORE-151: Pom file '.*/pom.xml' contains no reference to project-keeper-maven-plugin."
  - regex: "(?s)E-PK-CORE-18: Outdated content: 'exasol-(jdbc|s3)/pk_generated_parent.pom'"
  - regex: "(?s)E-PK-CORE-104: Invalid pom file 'exasol-(jdbc|s3)/pom.xml': Invalid /project/parent/artifactId.*"
  - regex: "(?s)E-PK-CORE-118: Invalid pom file 'exasol-(jdbc|s3)/pom.xml': Invalid /project/parent/version.*"
  - "E-PK-CORE-17: Missing required file: '.github/workflows/project-keeper-verify.yml'"
  - "E-PK-CORE-17: Missing required file: '.github/workflows/project-keeper.sh'"
linkReplacements:
  - https://netty.io/netty-all/|https://netty.io/index.html
  - http://nexus.sonatype.org/oss-repository-hosting.html/scalatest-maven-plugin|https://www.scalatest.org/user_guide/using_the_scalatest_maven_plugin
  - jquery.org/license|https://github.com/jquery/jquery/blob/main/LICENSE.txt
  - https://avro.apache.org/avro-mapred|https://avro.apache.org
  - https://projects.eclipse.org/projects/ee4j.jersey/project/jersey-media-jaxb|https://eclipse-ee4j.github.io/jersey/
  - https://developers.google.com/protocol-buffers/protobuf-java/|https://developers.google.com/protocol-buffers/docs/javatutorial
  - https://logging.apache.org/log4j/2.x/log4j-1.2-api/|https://logging.apache.org/log4j/2.x/
