name: CI Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Building with ${{ matrix.mvn.name }} and Exasol ${{ matrix.exasol-docker-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        exasol-docker-version: [ 7.0.14, 7.1.3 ]
        mvn:
          [
            {
              name: 'Spark3.2 and Scala 2.13',
              profile: '-Pspark3.2',
              project-keeper-skip: false,
            },
            {
              name: 'Spark3.2 and Scala 2.12',
              profile: '-Pspark3.2 -Pscala2.12',
              project-keeper-skip: true,
            },
            {
              name: 'Spark3.1 and Scala 2.12',
              profile: '-Pspark3.1',
              project-keeper-skip: true,
            },
            {
              name: 'Spark2.4 and Scala 2.12',
              profile: '-Pspark2.4',
              project-keeper-skip: true,
            },
          ]
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 11
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Cache SonarCloud packages
        uses: actions/cache@v2
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Pull docker Images
        run: docker pull exasol/docker-db:${{ matrix.exasol-docker-version }}
      - name: Run scalafix linting
        if: ${{ false }}
        run: |
          mvn --batch-mode clean compile test scalafix:scalafix ${{ matrix.mvn.profile }} \
              -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn \
              -DtrimStackTrace=false
      - name: Run tests and build with Maven
        run: |
          mvn --batch-mode verify ${{ matrix.mvn.profile }} \
              -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn \
              -DtrimStackTrace=false \
              -Dproject-keeper.skip=${{ matrix.mvn.project-keeper-skip }}
        env:
          EXASOL_DOCKER_VERSION: ${{ matrix.exasol-docker-version }}
      - name: Publish Test Report
        uses: scacap/action-surefire-report@v1
        if: ${{ always() && github.event.pull_request.head.repo.full_name == github.repository && github.actor != 'dependabot[bot]' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Sonar analysis
        if: ${{ env.SONAR_TOKEN != null && matrix.mvn.profile == '-Pspark3.2' }}
        run: |
          mvn --batch-mode sonar:sonar \
              -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn \
              -DtrimStackTrace=false \
              -Dsonar.organization=exasol \
              -Dsonar.host.url=https://sonarcloud.io \
              -Dsonar.login=$SONAR_TOKEN
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}