name: Release Droid - Print Quick Checksum

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - { profile: '-Pspark3.2', project-keeper-skip: false }
          - { profile: '-Pspark3.2 -Pscala2.12', project-keeper-skip: true }
          - { profile: '-Pspark3.1', project-keeper-skip: true }
          - { profile: '-Pspark2.4', project-keeper-skip: true }
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 11
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build with Maven skipping tests
        run: |
          mvn --batch-mode clean verify ${{ matrix.profile }} \
              -DskipTests \
              -Dproject-keeper.skip=${{ matrix.project-keeper-skip }}
      - name: Print checksum
        run: echo 'checksum_start==';find target -maxdepth 1 -name *.jar -exec sha256sum "{}" + | xargs;echo '==checksum_end'

