name: Release Droid - Release On Maven Central

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - { profile: '-Pspark3.2', project-keeper-skip: false }
          - { profile: '-Pspark3.2 -Pscala2.12', project-keeper-skip: true }
          - { profile: '-Pspark3.1', project-keeper-skip: true }
          - { profile: '-Pspark2.4', project-keeper-skip: true }
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 11
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - name: Import GPG Key
        run:
          gpg --import --batch <(echo "${{ secrets.OSSRH_GPG_SECRET_KEY }}")
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Publish to Central Repository
        run: |
          mvn clean deploy ${{ matrix.profile }} \
              -Dgpg.skip=false \
              -Dgpg.passphrase=${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }} \
              -DskipTests \
              -Dproject-keeper.skip=${{ matrix.project-keeper-skip }}
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
