name: Release Droid - Release On Maven Central

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        profile: [ '-Pspark3.2', '-Pspark3.2 -Pscala2.12', '-Pspark3.1', '-Pspark2.4' ]
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 11
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - name: Import GPG Key
        run:
          gpg --import --batch <(echo "${{ secrets.OSSRH_GPG_SECRET_KEY }}")
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Install xmlstarlet
        run: sudo apt install -y --no-install-recommends xmlstarlet
      - name: Create release pom file
        run: ./tools/createReleasePom.sh
      - name: Publish to Central Repository
        run: |
          mvn --file release.xml clean deploy ${{ matrix.profile }} \
              -Dgpg.skip=false \
              -Dgpg.passphrase=${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }} \
              -DskipTests \
              -Dproject-keeper.skip=false
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
      - name: Remove release pom file
        run: rm -rf release.xml
