name: Release Droid - Upload GitHub Release Assets

on:
  workflow_dispatch:
    inputs:
      upload_url:
        description: 'Assets upload URL'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - { profile: '-Pspark3.2', project-keeper-skip: false }
          - { profile: '-Pspark3.2 -Pscala2.12', project-keeper-skip: true }
          - { profile: '-Pspark3.1', project-keeper-skip: true }
          - { profile: '-Pspark2.4', project-keeper-skip: true }
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 11
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build with Maven skipping tests
        run: |
          mvn --batch-mode clean verify ${{ matrix.profile }} \
              -DskipTests \
              -Dproject-keeper.skip=${{ matrix.project-keeper-skip }}
      - name: Generate sha256sum files
        run: find target -maxdepth 1 -name *.jar -exec bash -c 'sha256sum {} > {}.sha256' \;
      - name: Upload assets to the GitHub release draft
        uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ github.event.inputs.upload_url }}
          asset_path: target/*.jar
      - name: Upload sha256sum files
        uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ github.event.inputs.upload_url }}
          asset_path: target/*.sha256
      - name: Upload error-code-report
        uses: shogo82148/actions-upload-release-asset@v1
        if: ${{ !matrix.project-keeper-skip }}
        with:
          upload_url: ${{ github.event.inputs.upload_url }}
          asset_path: target/error_code_report.json